apiVersion: v1
kind: Pod
metadata:
  name: nginx-volume-pod
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: nginx-storage

  volumes:
    - name: nginx-storage
      emptyDir: {}
